port: 2233

auth:
    hash_salt: "hash_salt"
    signing_key: "signing_key"
    token_ttl: 86400

psql:
    login: pedigree
    password: root
    ssl_mode: disable
    driver_name: postgres
    database_name: pedigree
    attempts_connection: 3