port: 2233

auth:
    hash_salt: "hash_salt"
    signing_key: "654684351849"
    token_duration: 8640000000000


psql:
    login: pedigree
    password: root
    ssl_mode: disable
    driver_name: postgres
    database_name: pedigree
    attempts_connection: 3